"""브로커 공통 인터페이스 (Protocol — duck typing 지원)"""
from typing import Callable, Protocol, runtime_checkable


@runtime_checkable
class BrokerBase(Protocol):
    def login(self) -> bool: ...
    def get_deposit(self, account: str) -> float: ...
    def get_current_price(self, ticker: str) -> float: ...
    def send_order(self, account: str, ticker: str,
                   order_type: str, quantity: int) -> bool: ...
    def subscribe_real(self, ticker: str,
                       callback: Callable[[str, float], None]): ...
    def unsubscribe_real(self, ticker: str): ...
